services:
  front:
    image: chatventure-front-ci
    build:
      context: ./frontend
    container_name: front
    environment:
      - VITE_BACKEND_URL=http://localhost:3001

  back:
    image: chatventure-back-ci
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./backend/.env:/usr/src/app/.env
    container_name: back
    environment:
      - MONGODB_URI=${MONGODB_URI}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
        - 80:80
    volumes:
        - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf
