services:
  front:
    image: chatventure-front-dev
    build:
      context: ./frontend
      args:
        VITE_GTM_ID: ${VITE_GTM_ID:-}
    container_name: front
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:3001

  back:
    image: chatventure-back-dev
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./backend/.env:/usr/src/app/.env
    container_name: back
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
        - 80:80
    volumes:
        - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf
