version: '3.8'

services:
  front:
    image: chat-frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    container_name: front
  back:
    image: chat-backend
    build:
      context: ./backend
    ports:
      - 3001:3001