services:
  front:
    image: chatventure-front-dev
    build:
      context: ./frontend
    container_name: front
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:3001

  back:
    image: chatventure-back-dev
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./backend/.env:/usr/src/app/.env
    environment:
      - MONGODB_URL=dummy
    container_name: back
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
        - 80:80
    volumes:
        - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf
    healthcheck:
        test: curl -f http://localhost || exit 1
        interval: 10s
        retries: 5
        start_period: 60s
        timeout: 10s
