version: '3.8'

services:
  front:
    image: chatventure-front-dev
    build:
      context: ./frontend
    container_name: front
    ports:
      - 3000:3000
  back:
    image: chatventure-back-dev
    build:
      context: ./backend
    volumes:
      - ./backend/.env:/usr/src/app/.env
    container_name: back
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
        - 80:80
    volumes:
        - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf
    healthcheck:
        test: curl -f http://localhost || exit 1
        interval: 10s
        retries: 5
        start_period: 20s
        timeout: 10s
    labels:
      autoheal: true
  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - AUTOHEAL_INTERVAL=10
      - CURL_TIMEOUT=30
  
  